In [166]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score, cross_validate

In [200]:
def transform_data(csv):
    df = pd.read_csv(csv)
    df = df.fillna({'Age': -1, 'Cabin': 'Unknown', 'Embarked': 'Unknown'})
    df['CabinLetter'] = df['Cabin'].str.slice(0,1)
    df['ParchGT0'] = df['Parch'] > 0
    df['SibSpGT0'] = df['SibSp'] > 0
    df['Name'] = df['Name'].str.lower()
    df['mr'] = df['Name'].str.contains('mr\.')
    df['mrs'] = df['Name'].str.contains('mrs\.')
    df['miss'] = df['Name'].str.contains('miss')
    df['master'] = df['Name'].str.contains('master')
    df['jr'] = df['Name'].str.contains('jr')
    df = pd.get_dummies(df, columns=['Pclass', 'Cabin', 'Embarked', 'CabinLetter', 'Sex'])
    
    vectorizer = CountVectorizer(min_df=.01)
    
    df = pd.concat([
        df,
        pd.DataFrame(vectorizer.fit_transform(df['Ticket']).toarray())
    ], axis=1)
    
    return df.loc[:,(df.dtypes =='int64') | (df.dtypes =='bool') | (df.dtypes =='float64')]


def transform_data(csv):
    df = pd.read_csv(csv)
    df = df.fillna({'Age': -1, 'Cabin': 'Unknown', 'Embarked': 'Unknown'})
    cols = ['PassengerId', 'Age', 'Sex', 'Pclass', 'Cabin', 'Name']
    if 'train' in csv:
        cols = ['Survived'] + cols
    df = df[cols]
    
    #df['CabinLetter'] = df['Cabin'].str.slice(0,1)
    df['master'] = df['Name'].str.contains('master')
    df['mr'] = df['Name'].str.contains('mr\.')
    df['mrs'] = df['Name'].str.contains('mrs\.')
    df['miss'] = df['Name'].str.contains('miss')
    
    #df['ParchGT0'] = df['Parch'] > 0
    #df['SibSpGT0'] = df['SibSp'] > 0
    
    df = pd.get_dummies(df, columns=['Sex', 'Pclass'])
    
    return df.loc[:,(df.dtypes =='int64') | (df.dtypes =='bool') | (df.dtypes =='float64')]

train = transform_data('train.csv')
test = transform_data('test.csv')

#train

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

Y = train[['Survived']].values
X = train.values[:,2:]
clf = RandomForestClassifier(n_estimators=500)
clf.fit(X,Y)
print('train:', accuracy_score(Y, clf.predict(X)))

#X_test = test.values[:,1:]
#Y_test = test[['Survived']].values
#print('train:', accuracy_score(Y_test, clf.predict(X_test)))

cross_validate(clf, X, Y.reshape(-1))

X_test = test.values[:,1:]
#Y_test = test[['Survived']].values
#print('train:', accuracy_score(Y_test, clf.predict(X_test)))
test['Survived'] = clf.predict(X_test)
test[['PassengerId', 'Survived']]

c:\Users\Jeremy\Anaconda3\lib\site-packages\ipykernel\__main__.py:57: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

train: 0.879910213244

     PassengerId  Survived
0            892         0
1            893         0
2            894         1
3            895         1
4            896         1
5            897         0
6            898         0
7            899         0
8            900         0
9            901         0
10           902         0
11           903         0
12           904         1
13           905         1
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         0
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         1
390         1282         1
391         1283         1
392         1284         1
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         1
404         1296         1
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         0
410         1302         1
411         1303         1
412         1304         0
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]

In [202]:
test[['PassengerId', 'Survived']].to_csv('submission.csv', index=False)

In [199]:
X_test = test.values[:,1:]
#Y_test = test[['Survived']].values
#print('train:', accuracy_score(Y_test, clf.predict(X_test)))
test['Survived'] = clf.predict(X_test)
test[['PassengerId', 'Survived']]

ValueError: Number of features of the model must match the input. Model n_features is 10 and input n_features is 11

In [172]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

Y = train[['Survived']].values
X = train.values[:,2:]
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X,Y)
print('train:', accuracy_score(Y, clf.predict(X)))

#X_test = test.values[:,1:]
#Y_test = test[['Survived']].values
#print('train:', accuracy_score(Y_test, clf.predict(X_test)))

cross_validate(clf, X, Y.reshape(-1))

c:\Users\Jeremy\Anaconda3\lib\site-packages\ipykernel\__main__.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

train: 0.989898989899

{'fit_time': array([ 0.11810446,  0.12111521,  0.11710286]),
 'score_time': array([ 0.00900936,  0.00801682,  0.00801706]),
 'test_score': array([ 0.78114478,  0.83501684,  0.8047138 ]),
 'train_score': array([ 0.99326599,  0.98821549,  0.99158249])}

In [170]:
Y.reshape(-1).shape

(891,)

In [171]:
cross_validate(clf, X, Y.reshape(-1))

{'fit_time': array([ 0.1191144 ,  0.12011528,  0.12012482]),
 'score_time': array([ 0.00901842,  0.00900865,  0.008008  ]),
 'test_score': array([ 0.76430976,  0.82491582,  0.8013468 ]),
 'train_score': array([ 0.99326599,  0.98821549,  0.99158249])}

In [135]:
train.loc[:,(train.dtypes =='int64') | (train.dtypes =='bool') | (train.dtypes =='float64')]

PassengerId           int64
Survived              int64
Age                 float64
SibSp                 int64
Parch                 int64
Fare                float64
ParchGT0               bool
SibSpGT0               bool
mr                     bool
mrs                    bool
miss                   bool
master                 bool
jr                     bool
Pclass_1            float64
Pclass_2            float64
Pclass_3            float64
Cabin_A10           float64
Cabin_A14           float64
Cabin_A16           float64
Cabin_A19           float64
Cabin_A20           float64
Cabin_A23           float64
Cabin_A24           float64
Cabin_A26           float64
Cabin_A31           float64
Cabin_A32           float64
Cabin_A34           float64
Cabin_A36           float64
Cabin_A5            float64
Cabin_A6            float64
                     ...
Cabin_E63           float64
Cabin_E67           float64
Cabin_E68           float64
Cabin_E77           float64
Cabin_E8            float64
Cabin_F E69         float64
Cabin_F G63         float64
Cabin_F G73         float64
Cabin_F2            float64
Cabin_F33           float64
Cabin_F38           float64
Cabin_F4            float64
Cabin_G6            float64
Cabin_T             float64
Cabin_Unknown       float64
Embarked_C          float64
Embarked_Q          float64
Embarked_S          float64
Embarked_Unknown    float64
CabinLetter_A       float64
CabinLetter_B       float64
CabinLetter_C       float64
CabinLetter_D       float64
CabinLetter_E       float64
CabinLetter_F       float64
CabinLetter_G       float64
CabinLetter_T       float64
CabinLetter_U       float64
Sex_female          float64
Sex_male            float64
dtype: object

In [115]:
train = transform_data('train.csv')

NameError: name 'data' is not defined

In [112]:
pd.get_dummies(train, columns=['Pclass', 'Cabin', 'Embarked', 'CabinLetter'])

,PassengerId,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,ParchGT0,...,Embarked_Unknown,CabinLetter_A,CabinLetter_B,CabinLetter_C,CabinLetter_D,CabinLetter_E,CabinLetter_F,CabinLetter_G,CabinLetter_T,CabinLetter_U
0,1,0,"braund, mr. owen harris",male,22.0,1,0,A/5 21171,7.2500,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,1,"cumings, mrs. john bradley (florence briggs th...",female,38.0,1,0,PC 17599,71.2833,False,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1,"heikkinen, miss. laina",female,26.0,0,0,STON/O2. 3101282,7.9250,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,1,"futrelle, mrs. jacques heath (lily may peel)",female,35.0,1,0,113803,53.1000,False,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,0,"allen, mr. william henry",male,35.0,0,0,373450,8.0500,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5,6,0,"moran, mr. james",male,100.0,0,0,330877,8.4583,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6,7,0,"mccarthy, mr. timothy j",male,54.0,0,0,17463,51.8625,False,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
7,8,0,"palsson, master. gosta leonard",male,2.0,3,1,349909,21.0750,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
8,9,1,"johnson, mrs. oscar w (elisabeth vilhelmina berg)",female,27.0,0,2,347742,11.1333,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
9,10,1,"nasser, mrs. nicholas (adele achem)",female,14.0,1,0,237736,30.0708,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,11,1,"sandstrom, miss. marguerite rut",female,4.0,1,1,PP 9549,16.7000,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
11,12,1,"bonnell, miss. elizabeth",female,58.0,0,0,113783,26.5500,False,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
12,13,0,"saundercock, mr. william henry",male,20.0,0,0,A/5. 2151,8.0500,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
13,14,0,"andersson, mr. anders johan",male,39.0,1,5,347082,31.2750,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
14,15,0,"vestrom, miss. hulda amanda adolfina",female,14.0,0,0,350406,7.8542,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,16,1,"hewlett, mrs. (mary d kingcome)",female,55.0,0,0,248706,16.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,17,0,"rice, master. eugene",male,2.0,4,1,382652,29.1250,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17,18,1,"williams, mr. charles eugene",male,100.0,0,0,244373,13.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,19,0,"vander planke, mrs. julius (emelia maria vande...",female,31.0,1,0,345763,18.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
19,20,1,"masselmani, mrs. fatima",female,100.0,0,0,2649,7.2250,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20,21,0,"fynney, mr. joseph j",male,35.0,0,0,239865,26.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
21,22,1,"beesley, mr. lawrence",male,34.0,0,0,248698,13.0000,False,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
22,23,1,"mcgowan, miss. anna ""annie""",female,15.0,0,0,330923,8.0292,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
23,24,1,"sloper, mr. william thompson",male,28.0,0,0,113788,35.5000,False,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,25,0,"palsson, miss. torborg danira",female,8.0,3,1,349909,21.0750,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
25,26,1,"asplund, mrs. carl oscar (selma augusta emilia...",female,38.0,1,5,347077,31.3875,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
26,27,0,"emir, mr. farred chehab",male,100.0,0,0,2631,7.2250,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
27,28,0,"fortune, mr. charles alexander",male,19.0,3,2,19950,263.0000,True,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
28,29,1,"o'dwyer, miss. ellen ""nellie""",female,100.0,0,0,330959,7.8792,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
29,30,0,"todoroff, mr. lalio",male,100.0,0,0,349216,7.8958,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,"giles, mr. frederick edward",male,21.0,1,0,28134,11.5000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
862,863,1,"swift, mrs. frederick joel (margaret welles ba...",female,48.0,0,0,17466,25.9292,False,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
863,864,0,"sage, miss. dorothy edith ""dolly""",female,100.0,8,2,CA. 2343,69.5500,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
864,865,0,"gill, mr. john william",male,24.0,0,0,233866,13.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
865,866,1,"bystrom, mrs. (karolina)",female,42.0,0,0,236852,13.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
866,867,1,"duran y more, miss. asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
867,868,0,"roebling, mr. washington augustus ii",male,31.0,0,0,PC 17590,50.4958,False,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
868,869,0,"van melkebeke, mr. philemon",male,100.0,0,0,345777,9.5000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
869,870,1,"johnson, master. harold theodor",male,4.0,1,1,347742,11.1333,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
870,871,0,"balkic, mr. cerin",male,26.0,0,0,349248,7.8958,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
871,872,1,"beckwith, mrs. richard leonard (sallie monypeny)",female,47.0,1,1,11751,52.5542,True,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
872,873,0,"carlsson, mr. frans olof",male,33.0,0,0,695,5.0000,False,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
873,874,0,"vander cruyssen, mr. victor",male,47.0,0,0,345765,9.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
874,875,1,"abelson, mrs. samuel (hannah wizosky)",female,28.0,1,0,P/PP 3381,24.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
875,876,1,"najib, miss. adele kiamie ""jane""",female,15.0,0,0,2667,7.2250,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
876,877,0,"gustafsson, mr. alfred ossian",male,20.0,0,0,7534,9.8458,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
877,878,0,"petroff, mr. nedelio",male,19.0,0,0,349212,7.8958,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
878,879,0,"laleff, mr. kristo",male,100.0,0,0,349217,7.8958,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
879,880,1,"potter, mrs. thomas jr (lily alexenia wilson)",female,56.0,0,1,11767,83.1583,True,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
880,881,1,"shelley, mrs. william (imanita parrish hall)",female,25.0,0,1,230433,26.0000,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
881,882,0,"markun, mr. johann",male,33.0,0,0,349257,7.8958,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
882,883,0,"dahlberg, miss. gerda ulrika",female,22.0,0,0,7552,10.5167,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
883,884,0,"banfield, mr. frederick james",male,28.0,0,0,C.A./SOTON 34068,10.5000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
884,885,0,"sutehall, mr. henry jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
885,886,0,"rice, mrs. william (margaret norton)",female,39.0,0,5,382652,29.1250,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
886,887,0,"montvila, rev. juozas",male,27.0,0,0,211536,13.0000,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
887,888,1,"graham, miss. margaret edith",female,19.0,0,0,112053,30.0000,False,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
888,889,0,"johnston, miss. catherine helen ""carrie""",female,100.0,1,2,W./C. 6607,23.4500,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
889,890,1,"behr, mr. karl howell",male,26.0,0,0,111369,30.0000,False,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
890,891,0,"dooley, mr. patrick",male,32.0,0,0,370376,7.7500,False,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [61]:
train['Name'].unique()

array(['Braund, Mr. Owen Harris',
       'Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Heikkinen, Miss. Laina',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'Allen, Mr. William Henry', 'Moran, Mr. James',
       'McCarthy, Mr. Timothy J', 'Palsson, Master. Gosta Leonard',
       'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)',
       'Nasser, Mrs. Nicholas (Adele Achem)',
       'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth',
       'Saundercock, Mr. William Henry', 'Andersson, Mr. Anders Johan',
       'Vestrom, Miss. Hulda Amanda Adolfina',
       'Hewlett, Mrs. (Mary D Kingcome) ', 'Rice, Master. Eugene',
       'Williams, Mr. Charles Eugene',
       'Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)',
       'Masselmani, Mrs. Fatima', 'Fynney, Mr. Joseph J',
       'Beesley, Mr. Lawrence', 'McGowan, Miss. Anna "Annie"',
       'Sloper, Mr. William Thompson', 'Palsson, Miss. Torborg Danira',
       'Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)',
       'Emir, Mr. Farred Chehab', 'Fortune, Mr. Charles Alexander',
       'O\'Dwyer, Miss. Ellen "Nellie"', 'Todoroff, Mr. Lalio',
       'Uruchurtu, Don. Manuel E',
       'Spencer, Mrs. William Augustus (Marie Eugenie)',
       'Glynn, Miss. Mary Agatha', 'Wheadon, Mr. Edward H',
       'Meyer, Mr. Edgar Joseph', 'Holverson, Mr. Alexander Oskar',
       'Mamee, Mr. Hanna', 'Cann, Mr. Ernest Charles',
       'Vander Planke, Miss. Augusta Maria', 'Nicola-Yarred, Miss. Jamila',
       'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
       'Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)',
       'Kraeff, Mr. Theodor', 'Laroche, Miss. Simonne Marie Anne Andree',
       'Devaney, Miss. Margaret Delia', 'Rogers, Mr. William John',
       'Lennon, Mr. Denis', "O'Driscoll, Miss. Bridget",
       'Samaan, Mr. Youssef',
       'Arnold-Franchi, Mrs. Josef (Josefine Franchi)',
       'Panula, Master. Juha Niilo', 'Nosworthy, Mr. Richard Cater',
       'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
       'Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)',
       'Ostby, Mr. Engelhart Cornelius', 'Woolner, Mr. Hugh',
       'Rugg, Miss. Emily', 'Novel, Mr. Mansouer',
       'West, Miss. Constance Mirium',
       'Goodwin, Master. William Frederick', 'Sirayanian, Mr. Orsen',
       'Icard, Miss. Amelie', 'Harris, Mr. Henry Birkhardt',
       'Skoog, Master. Harald', 'Stewart, Mr. Albert A',
       'Moubarek, Master. Gerios', 'Nye, Mrs. (Elizabeth Ramell)',
       'Crease, Mr. Ernest James', 'Andersson, Miss. Erna Alexandra',
       'Kink, Mr. Vincenz', 'Jenkin, Mr. Stephen Curnow',
       'Goodwin, Miss. Lillian Amy', 'Hood, Mr. Ambrose Jr',
       'Chronopoulos, Mr. Apostolos', 'Bing, Mr. Lee',
       'Moen, Mr. Sigurd Hansen', 'Staneff, Mr. Ivan',
       'Moutal, Mr. Rahamin Haim', 'Caldwell, Master. Alden Gates',
       'Dowdell, Miss. Elizabeth', 'Waelens, Mr. Achille',
       'Sheerlinck, Mr. Jan Baptist', 'McDermott, Miss. Brigdet Delia',
       'Carrau, Mr. Francisco M', 'Ilett, Miss. Bertha',
       'Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)',
       'Ford, Mr. William Neal', 'Slocovski, Mr. Selman Francis',
       'Fortune, Miss. Mabel Helen', 'Celotti, Mr. Francesco',
       'Christmann, Mr. Emil', 'Andreasson, Mr. Paul Edvin',
       'Chaffee, Mr. Herbert Fuller', 'Dean, Mr. Bertram Frank',
       'Coxon, Mr. Daniel', 'Shorney, Mr. Charles Joseph',
       'Goldschmidt, Mr. George B', 'Greenfield, Mr. William Bertram',
       'Doling, Mrs. John T (Ada Julia Bone)', 'Kantor, Mr. Sinai',
       'Petranec, Miss. Matilda', 'Petroff, Mr. Pastcho ("Pentcho")',
       'White, Mr. Richard Frasar', 'Johansson, Mr. Gustaf Joel',
       'Gustafsson, Mr. Anders Vilhelm', 'Mionoff, Mr. Stoytcho',
       'Salkjelsvik, Miss. Anna Kristine', 'Moss, Mr. Albert Johan',
       'Rekic, Mr. Tido', 'Moran, Miss. Bertha',
       'Porter, Mr. Walter Chamberlain', 'Zabour, Miss. Hileni',
       'Barton, Mr. David John', 'Jussila, Miss. Katriina',
       'Attalah, Miss. Malake', 'Pekoniemi, Mr. Edvard',
       'Connors, Mr. Patrick', 'Turpin, Mr. William John Robert',
       'Baxter, Mr. Quigg Edmond', 'Andersson, Miss. Ellis Anna Maria',
       'Hickman, Mr. Stanley George', 'Moore, Mr. Leonard Charles',
       'Nasser, Mr. Nicholas', 'Webber, Miss. Susan',
       'White, Mr. Percival Wayland', 'Nicola-Yarred, Master. Elias',
       'McMahon, Mr. Martin', 'Madsen, Mr. Fridtjof Arne',
       'Peter, Miss. Anna', 'Ekstrom, Mr. Johan', 'Drazenoic, Mr. Jozef',
       'Coelho, Mr. Domingos Fernandeo',
       'Robins, Mrs. Alexander A (Grace Charity Laury)',
       'Weisz, Mrs. Leopold (Mathilde Francoise Pede)',
       'Sobey, Mr. Samuel James Hayden', 'Richard, Mr. Emile',
       'Newsom, Miss. Helen Monypeny', 'Futrelle, Mr. Jacques Heath',
       'Osen, Mr. Olaf Elon', 'Giglio, Mr. Victor',
       'Boulos, Mrs. Joseph (Sultana)', 'Nysten, Miss. Anna Sofia',
       'Hakkarainen, Mrs. Pekka Pietari (Elin Matilda Dolck)',
       'Burke, Mr. Jeremiah', 'Andrew, Mr. Edgardo Samuel',
       'Nicholls, Mr. Joseph Charles',
       'Andersson, Mr. August Edvard ("Wennerstrom")',
       'Ford, Miss. Robina Maggie "Ruby"',
       'Navratil, Mr. Michel ("Louis M Hoffman")',
       'Byles, Rev. Thomas Roussel Davids', 'Bateman, Rev. Robert James',
       'Pears, Mrs. Thomas (Edith Wearne)', 'Meo, Mr. Alfonzo',
       'van Billiard, Mr. Austin Blyler', 'Olsen, Mr. Ole Martin',
       'Williams, Mr. Charles Duane', 'Gilnagh, Miss. Katherine "Katie"',
       'Corn, Mr. Harry', 'Smiljanic, Mr. Mile',
       'Sage, Master. Thomas Henry', 'Cribb, Mr. John Hatfield',
       'Watt, Mrs. James (Elizabeth "Bessie" Inglis Milne)',
       'Bengtsson, Mr. John Viktor', 'Calic, Mr. Jovo',
       'Panula, Master. Eino Viljami',
       'Goldsmith, Master. Frank John William "Frankie"',
       'Chibnall, Mrs. (Edith Martha Bowerman)',
       'Skoog, Mrs. William (Anna Bernhardina Karlsson)',
       'Baumann, Mr. John D', 'Ling, Mr. Lee', 'Van der hoef, Mr. Wyckoff',
       'Rice, Master. Arthur', 'Johnson, Miss. Eleanor Ileen',
       'Sivola, Mr. Antti Wilhelm', 'Smith, Mr. James Clinch',
       'Klasen, Mr. Klas Albin', 'Lefebre, Master. Henry Forbes',
       'Isham, Miss. Ann Elizabeth', 'Hale, Mr. Reginald',
       'Leonard, Mr. Lionel', 'Sage, Miss. Constance Gladys',
       'Pernot, Mr. Rene', 'Asplund, Master. Clarence Gustaf Hugo',
       'Becker, Master. Richard F', 'Kink-Heilmann, Miss. Luise Gretchen',
       'Rood, Mr. Hugh Roscoe',
       'O\'Brien, Mrs. Thomas (Johanna "Hannah" Godfrey)',
       'Romaine, Mr. Charles Hallace ("Mr C Rolmane")', 'Bourke, Mr. John',
       'Turcin, Mr. Stjepan', 'Pinsky, Mrs. (Rosa)',
       'Carbines, Mr. William',
       'Andersen-Jensen, Miss. Carla Christine Nielsine',
       'Navratil, Master. Michel M',
       'Brown, Mrs. James Joseph (Margaret Tobin)', 'Lurette, Miss. Elise',
       'Mernagh, Mr. Robert', 'Olsen, Mr. Karl Siegwart Andreas',
       'Madigan, Miss. Margaret "Maggie"',
       'Yrois, Miss. Henriette ("Mrs Harbeck")',
       'Vande Walle, Mr. Nestor Cyriel', 'Sage, Mr. Frederick',
       'Johanson, Mr. Jakob Alfred', 'Youseff, Mr. Gerious',
       'Cohen, Mr. Gurshon "Gus"', 'Strom, Miss. Telma Matilda',
       'Backstrom, Mr. Karl Alfred', 'Albimona, Mr. Nassef Cassem',
       'Carr, Miss. Helen "Ellen"', 'Blank, Mr. Henry', 'Ali, Mr. Ahmed',
       'Cameron, Miss. Clear Annie', 'Perkin, Mr. John Henry',
       'Givard, Mr. Hans Kristensen', 'Kiernan, Mr. Philip',
       'Newell, Miss. Madeleine', 'Honkanen, Miss. Eliina',
       'Jacobsohn, Mr. Sidney Samuel', 'Bazzani, Miss. Albina',
       'Harris, Mr. Walter', 'Sunderland, Mr. Victor Francis',
       'Bracken, Mr. James H', 'Green, Mr. George Henry',
       'Nenkoff, Mr. Christo', 'Hoyt, Mr. Frederick Maxfield',
       'Berglund, Mr. Karl Ivar Sven', 'Mellors, Mr. William John',
       'Lovell, Mr. John Hall ("Henry")', 'Fahlstrom, Mr. Arne Jonas',
       'Lefebre, Miss. Mathilde',
       'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
       'Larsson, Mr. Bengt Edvin', 'Sjostedt, Mr. Ernst Adolf',
       'Asplund, Miss. Lillian Gertrud',
       'Leyson, Mr. Robert William Norman', 'Harknett, Miss. Alice Phoebe',
       'Hold, Mr. Stephen', 'Collyer, Miss. Marjorie "Lottie"',
       'Pengelly, Mr. Frederick William', 'Hunt, Mr. George Henry',
       'Zabour, Miss. Thamine', 'Murphy, Miss. Katherine "Kate"',
       'Coleridge, Mr. Reginald Charles', 'Maenpaa, Mr. Matti Alexanteri',
       'Attalah, Mr. Sleiman', 'Minahan, Dr. William Edward',
       'Lindahl, Miss. Agda Thorilda Viktoria',
       'Hamalainen, Mrs. William (Anna)', 'Beckwith, Mr. Richard Leonard',
       'Carter, Rev. Ernest Courtenay', 'Reed, Mr. James George',
       'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
       'Stead, Mr. William Thomas', 'Lobb, Mr. William Arthur',
       'Rosblom, Mrs. Viktor (Helena Wilhelmina)',
       'Touma, Mrs. Darwis (Hanne Youssef Razi)',
       'Thorne, Mrs. Gertrude Maybelle', 'Cherry, Miss. Gladys',
       'Ward, Miss. Anna', 'Parrish, Mrs. (Lutie Davis)',
       'Smith, Mr. Thomas', 'Asplund, Master. Edvin Rojj Felix',
       'Taussig, Mr. Emil', 'Harrison, Mr. William', 'Henry, Miss. Delia',
       'Reeves, Mr. David', 'Panula, Mr. Ernesti Arvid',
       'Persson, Mr. Ernst Ulrik',
       'Graham, Mrs. William Thompson (Edith Junkins)',
       'Bissette, Miss. Amelia', 'Cairns, Mr. Alexander',
       'Tornquist, Mr. William Henry',
       'Mellinger, Mrs. (Elizabeth Anne Maidment)',
       'Natsch, Mr. Charles H', 'Healy, Miss. Hanora "Nora"',
       'Andrews, Miss. Kornelia Theodosia',
       'Lindblom, Miss. Augusta Charlotta', 'Parkes, Mr. Francis "Frank"',
       'Rice, Master. Eric', 'Abbott, Mrs. Stanton (Rosa Hunt)',
       'Duane, Mr. Frank', 'Olsson, Mr. Nils Johan Goransson',
       'de Pelsmaeker, Mr. Alfons', 'Dorking, Mr. Edward Arthur',
       'Smith, Mr. Richard William', 'Stankovic, Mr. Ivan',
       'de Mulder, Mr. Theodore', 'Naidenoff, Mr. Penko',
       'Hosono, Mr. Masabumi', 'Connolly, Miss. Kate',
       'Barber, Miss. Ellen "Nellie"',
       'Bishop, Mrs. Dickinson H (Helen Walton)', 'Levy, Mr. Rene Jacques',
       'Haas, Miss. Aloisia', 'Mineff, Mr. Ivan', 'Lewy, Mr. Ervin G',
       'Hanna, Mr. Mansour', 'Allison, Miss. Helen Loraine',
       'Saalfeld, Mr. Adolphe',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Kelly, Miss. Anna Katherine "Annie Kate"', 'McCoy, Mr. Bernard',
       'Johnson, Mr. William Cahoone Jr', 'Keane, Miss. Nora A',
       'Williams, Mr. Howard Hugh "Harry"',
       'Allison, Master. Hudson Trevor', 'Fleming, Miss. Margaret',
       'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       'Abelson, Mr. Samuel', 'Francatelli, Miss. Laura Mabel',
       'Hays, Miss. Margaret Bechstein', 'Ryerson, Miss. Emily Borie',
       'Lahtinen, Mrs. William (Anna Sylfven)', 'Hendekovic, Mr. Ignjac',
       'Hart, Mr. Benjamin', 'Nilsson, Miss. Helmina Josefina',
       'Kantor, Mrs. Sinai (Miriam Sternin)', 'Moraweck, Dr. Ernest',
       'Wick, Miss. Mary Natalie',
       'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
       'Dennis, Mr. Samuel', 'Danoff, Mr. Yoto',
       'Slayter, Miss. Hilda Mary',
       'Caldwell, Mrs. Albert Francis (Sylvia Mae Harbaugh)',
       'Sage, Mr. George John Jr', 'Young, Miss. Marie Grice',
       'Nysveen, Mr. Johan Hansen', 'Ball, Mrs. (Ada E Hall)',
       'Goldsmith, Mrs. Frank John (Emily Alice Brown)',
       'Hippach, Miss. Jean Gertrude', 'McCoy, Miss. Agnes',
       'Partner, Mr. Austen', 'Graham, Mr. George Edward',
       'Vander Planke, Mr. Leo Edmondus',
       'Frauenthal, Mrs. Henry William (Clara Heinsheimer)',
       'Denkoff, Mr. Mitto', 'Pears, Mr. Thomas Clinton',
       'Burns, Miss. Elizabeth Margaret', 'Dahl, Mr. Karl Edwart',
       'Blackwell, Mr. Stephen Weart', 'Navratil, Master. Edmond Roger',
       'Fortune, Miss. Alice Elizabeth', 'Collander, Mr. Erik Gustaf',
       'Sedgwick, Mr. Charles Frederick Waddington',
       'Fox, Mr. Stanley Hubert', 'Brown, Miss. Amelia "Mildred"',
       'Smith, Miss. Marion Elsie',
       'Davison, Mrs. Thomas Henry (Mary E Finck)',
       'Coutts, Master. William Loch "William"', 'Dimic, Mr. Jovan',
       'Odahl, Mr. Nils Martin', 'Williams-Lambert, Mr. Fletcher Fellows',
       'Elias, Mr. Tannous', 'Arnold-Franchi, Mr. Josef',
       'Yousif, Mr. Wazli', 'Vanden Steen, Mr. Leo Peter',
       'Bowerman, Miss. Elsie Edith', 'Funk, Miss. Annie Clemmer',
       'McGovern, Miss. Mary', 'Mockler, Miss. Helen Mary "Ellie"',
       'Skoog, Mr. Wilhelm', 'del Carlo, Mr. Sebastiano',
       'Barbara, Mrs. (Catherine David)', 'Asim, Mr. Adola',
       "O'Brien, Mr. Thomas", 'Adahl, Mr. Mauritz Nils Martin',
       'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
       'Moussa, Mrs. (Mantoura Boulos)', 'Jermyn, Miss. Annie',
       'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles',
       'Wiklund, Mr. Jakob Alfred', 'Beavan, Mr. William Thomas',
       'Ringhini, Mr. Sante', 'Palsson, Miss. Stina Viola',
       'Meyer, Mrs. Edgar Joseph (Leila Saks)',
       'Landergren, Miss. Aurora Adelia', 'Widener, Mr. Harry Elkins',
       'Betros, Mr. Tannous', 'Gustafsson, Mr. Karl Gideon',
       'Bidois, Miss. Rosalie', 'Nakid, Miss. Maria ("Mary")',
       'Tikkanen, Mr. Juho',
       'Holverson, Mrs. Alexander Oskar (Mary Aline Towner)',
       'Plotcharsky, Mr. Vasil', 'Davies, Mr. Charles Henry',
       'Goodwin, Master. Sidney Leonard', 'Buss, Miss. Kate',
       'Sadlier, Mr. Matthew', 'Lehmann, Miss. Bertha',
       'Carter, Mr. William Ernest', 'Jansson, Mr. Carl Olof',
       'Gustafsson, Mr. Johan Birger', 'Newell, Miss. Marjorie',
       'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
       'Johansson, Mr. Erik', 'Olsson, Miss. Elina',
       'McKane, Mr. Peter David', 'Pain, Dr. Alfred',
       'Trout, Mrs. William H (Jessie L)', 'Niskanen, Mr. Juha',
       'Adams, Mr. John', 'Jussila, Miss. Mari Aina',
       'Hakkarainen, Mr. Pekka Pietari', 'Oreskovic, Miss. Marija',
       'Gale, Mr. Shadrach', 'Widegren, Mr. Carl/Charles Peter',
       'Richards, Master. William Rowe',
       'Birkeland, Mr. Hans Martin Monsen', 'Lefebre, Miss. Ida',
       'Sdycoff, Mr. Todor', 'Hart, Mr. Henry', 'Minahan, Miss. Daisy E',
       'Cunningham, Mr. Alfred Fleming', 'Sundman, Mr. Johan Julian',
       'Meek, Mrs. Thomas (Annie Louise Rowley)',
       'Drew, Mrs. James Vivian (Lulu Thorne Christian)',
       'Silven, Miss. Lyyli Karoliina', 'Matthews, Mr. William John',
       'Van Impe, Miss. Catharina', 'Gheorgheff, Mr. Stanio',
       'Charters, Mr. David', 'Zimmerman, Mr. Leo',
       'Danbom, Mrs. Ernst Gilbert (Anna Sigrid Maria Brogren)',
       'Rosblom, Mr. Viktor Richard', 'Wiseman, Mr. Phillippe',
       'Clarke, Mrs. Charles V (Ada Maria Winfield)',
       'Phillips, Miss. Kate Florence ("Mrs Kate Louise Phillips Marshall")',
       'Flynn, Mr. James', 'Pickard, Mr. Berk (Berk Trembisky)',
       'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
       'Thorneycroft, Mrs. Percival (Florence Kate White)',
       'Louch, Mrs. Charles Alexander (Alice Adelaide Slow)',
       'Kallio, Mr. Nikolai Erland', 'Silvey, Mr. William Baird',
       'Carter, Miss. Lucile Polk', 'Ford, Miss. Doolina Margaret "Daisy"',
       'Richards, Mrs. Sidney (Emily Hocking)', 'Fortune, Mr. Mark',
       'Kvillner, Mr. Johan Henrik Johannesson',
       'Hart, Mrs. Benjamin (Esther Ada Bloomfield)', 'Hampe, Mr. Leon',
       'Petterson, Mr. Johan Emil', 'Reynaldo, Ms. Encarnacion',
       'Johannesen-Bratthammer, Mr. Bernt', 'Dodge, Master. Washington',
       'Mellinger, Miss. Madeleine Violet', 'Seward, Mr. Frederic Kimber',
       'Baclini, Miss. Marie Catherine', 'Peuchen, Major. Arthur Godfrey',
       'West, Mr. Edwy Arthur', 'Hagland, Mr. Ingvald Olai Olsen',
       'Foreman, Mr. Benjamin Laventall', 'Goldenberg, Mr. Samuel L',
       'Peduzzi, Mr. Joseph', 'Jalsevac, Mr. Ivan',
       'Millet, Mr. Francis Davis', 'Kenyon, Mrs. Frederick R (Marion)',
       'Toomey, Miss. Ellen', "O'Connor, Mr. Maurice",
       'Anderson, Mr. Harry', 'Morley, Mr. William', 'Gee, Mr. Arthur H',
       'Milling, Mr. Jacob Christian', 'Maisner, Mr. Simon',
       'Goncalves, Mr. Manuel Estanslas', 'Campbell, Mr. William',
       'Smart, Mr. John Montgomery', 'Scanlan, Mr. James',
       'Baclini, Miss. Helene Barbara', 'Keefe, Mr. Arthur',
       'Cacic, Mr. Luka', 'West, Mrs. Edwy Arthur (Ada Mary Worth)',
       'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
       'Strandberg, Miss. Ida Sofia', 'Clifford, Mr. George Quincy',
       'Renouf, Mr. Peter Henry', 'Braund, Mr. Lewis Richard',
       'Karlsson, Mr. Nils August', 'Hirvonen, Miss. Hildur E',
       'Goodwin, Master. Harold Victor',
       'Frost, Mr. Anthony Wood "Archie"', 'Rouse, Mr. Richard Henry',
       'Turkula, Mrs. (Hedwig)', 'Bishop, Mr. Dickinson H',
       'Lefebre, Miss. Jeannie',
       'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
       'Kent, Mr. Edward Austin', 'Somerton, Mr. Francis William',
       'Coutts, Master. Eden Leslie "Neville"',
       'Hagland, Mr. Konrad Mathias Reiersen', 'Windelov, Mr. Einar',
       'Molson, Mr. Harry Markland', 'Artagaveytia, Mr. Ramon',
       'Stanley, Mr. Edward Roland', 'Yousseff, Mr. Gerious',
       'Eustis, Miss. Elizabeth Mussey', 'Shellard, Mr. Frederick William',
       'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
       'Svensson, Mr. Olof', 'Calic, Mr. Petar', 'Canavan, Miss. Mary',
       "O'Sullivan, Miss. Bridget Mary", 'Laitinen, Miss. Kristina Sofia',
       'Maioni, Miss. Roberta',
       'Penasco y Castellana, Mr. Victor de Satode',
       'Quick, Mrs. Frederick Charles (Jane Richards)',
       'Bradley, Mr. George ("George Arthur Brayton")',
       'Olsen, Mr. Henry Margido', 'Lang, Mr. Fang',
       'Daly, Mr. Eugene Patrick', 'Webber, Mr. James',
       'McGough, Mr. James Robert',
       'Rothschild, Mrs. Martin (Elizabeth L. Barrett)',
       'Coleff, Mr. Satio', 'Walker, Mr. William Anderson',
       'Lemore, Mrs. (Amelia Milley)', 'Ryan, Mr. Patrick',
       'Angle, Mrs. William A (Florence "Mary" Agnes Hughes)',
       'Pavlovic, Mr. Stefo', 'Perreault, Miss. Anne', 'Vovk, Mr. Janko',
       'Lahoud, Mr. Sarkis',
       'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
       'Kassem, Mr. Fared', 'Farrell, Mr. James', 'Ridsdale, Miss. Lucy',
       'Farthing, Mr. John', 'Salonen, Mr. Johan Werner',
       'Hocking, Mr. Richard George', 'Quick, Miss. Phyllis May',
       'Toufik, Mr. Nakli', 'Elias, Mr. Joseph Jr',
       'Peter, Mrs. Catherine (Catherine Rizk)', 'Cacic, Miss. Marija',
       'Hart, Miss. Eva Miriam', 'Butt, Major. Archibald Willingham',
       'LeRoy, Miss. Bertha', 'Risien, Mr. Samuel Beard',
       'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R',
       'Andersson, Miss. Ingeborg Constanzia',
       'Andersson, Miss. Sigrid Elisabeth', 'Beane, Mr. Edward',
       'Douglas, Mr. Walter Donald', 'Nicholson, Mr. Arthur Ernest',
       'Beane, Mrs. Edward (Ethel Clarke)', 'Padro y Manent, Mr. Julian',
       'Goldsmith, Mr. Frank John', 'Davies, Master. John Morgan Jr',
       'Thayer, Mr. John Borland Jr', 'Sharp, Mr. Percival James R',
       "O'Brien, Mr. Timothy", 'Leeni, Mr. Fahim ("Philip Zenni")',
       'Ohman, Miss. Velin', 'Wright, Mr. George',
       'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
       'Robbins, Mr. Victor', 'Taussig, Mrs. Emil (Tillie Mandelbaum)',
       'de Messemaeker, Mrs. Guillaume Joseph (Emma)',
       'Morrow, Mr. Thomas Rowan', 'Sivic, Mr. Husein',
       'Norman, Mr. Robert Douglas', 'Simmons, Mr. John',
       'Meanwell, Miss. (Marion Ogden)', 'Davies, Mr. Alfred J',
       'Stoytcheff, Mr. Ilia',
       'Palsson, Mrs. Nils (Alma Cornelia Berglund)',

In [71]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=.01)
vectorizer.fit_transform(train['Name'].unique())
vectorizer.vocabulary_

{'alexander': 0,
 'alfred': 1,
 'andersson': 2,
 'anna': 3,
 'arthur': 4,
 'charles': 5,
 'edward': 6,
 'elizabeth': 7,
 'ernest': 8,
 'frederick': 9,
 'george': 10,
 'henry': 11,
 'james': 12,
 'johan': 13,
 'john': 14,
 'joseph': 15,
 'jr': 16,
 'karl': 17,
 'leonard': 18,
 'margaret': 19,
 'maria': 20,
 'mary': 21,
 'master': 22,
 'miss': 23,
 'mr': 24,
 'mrs': 25,
 'peter': 26,
 'richard': 27,
 'robert': 28,
 'samuel': 29,
 'thomas': 30,
 'william': 31}

In [88]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(min_df=.01)
#vectorizer.fit_transform(train['Ticket'])
#vectorizer.vocabulary_

train = pd.concat([
    train,
    pd.DataFrame(vectorizer.fit_transform(train['Ticket']).toarray())
], axis=1)

{'ca': 0, 'paris': 1, 'pc': 2, 'sc': 3, 'soton': 4, 'ston': 5}

In [90]:
vectorizer.fit_transform(train['Ticket']).toarray()

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [100]:
train = pd.concat([
    train,
    pd.DataFrame(vectorizer.fit_transform(train['Ticket']).toarray())
], axis=1)

In [108]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,mrs,miss,master,jr,0,1,2,3,4,5
0,0,0,0,0,0,0,1,0,A/5 21171,7.2500,...,False,False,False,False,0,0,0,0,0,0
1,0,0,1,0,0,0,1,0,PC 17599,71.2833,...,True,False,False,False,0,0,1,0,0,0
2,0,0,0,0,0,1,0,0,STON/O2. 3101282,7.9250,...,False,True,False,False,0,0,0,0,0,1
3,0,0,0,0,0,0,1,0,113803,53.1000,...,True,False,False,False,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,373450,8.0500,...,False,False,False,False,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,330877,8.4583,...,False,False,False,False,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,17463,51.8625,...,False,False,False,False,0,0,0,0,0,0
7,0,0,0,0,0,0,3,1,349909,21.0750,...,False,False,True,False,0,0,0,0,0,0
8,0,0,0,0,0,0,0,2,347742,11.1333,...,True,False,False,False,0,0,0,0,0,0
9,0,0,0,0,0,0,1,0,237736,30.0708,...,True,False,False,False,0,0,0,0,0,0
10,0,0,0,0,0,0,1,1,PP 9549,16.7000,...,False,True,False,False,0,0,0,0,0,0
11,0,0,0,0,0,0,0,0,113783,26.5500,...,False,True,False,False,0,0,0,0,0,0
12,0,0,0,0,0,0,0,0,A/5. 2151,8.0500,...,False,False,False,False,0,0,0,0,0,0
13,0,0,0,0,0,0,1,5,347082,31.2750,...,False,False,False,False,0,0,0,0,0,0
14,0,0,0,0,0,0,0,0,350406,7.8542,...,False,True,False,False,0,0,0,0,0,0
15,0,0,0,0,0,0,0,0,248706,16.0000,...,True,False,False,False,0,0,0,0,0,0
16,0,0,0,0,0,0,4,1,382652,29.1250,...,False,False,True,False,0,0,0,0,0,0
17,0,0,0,0,0,0,0,0,244373,13.0000,...,False,False,False,False,0,0,0,0,0,0
18,0,0,0,0,0,0,1,0,345763,18.0000,...,True,False,False,False,0,0,0,0,0,0
19,0,0,0,0,0,0,0,0,2649,7.2250,...,True,False,False,False,0,0,0,0,0,0
20,0,0,0,0,0,0,0,0,239865,26.0000,...,False,False,False,False,0,0,0,0,0,0
21,0,0,0,0,0,0,0,0,248698,13.0000,...,False,False,False,False,0,0,0,0,0,0
22,0,0,0,0,0,0,0,0,330923,8.0292,...,False,True,False,False,0,0,0,0,0,0
23,0,0,0,0,0,0,0,0,113788,35.5000,...,False,False,False,False,0,0,0,0,0,0
24,0,0,0,0,0,0,3,1,349909,21.0750,...,False,True,False,False,0,0,0,0,0,0
25,0,0,0,0,0,0,1,5,347077,31.3875,...,True,False,False,False,0,0,0,0,0,0
26,0,0,0,0,0,0,0,0,2631,7.2250,...,False,False,False,False,0,0,0,0,0,0
27,0,0,0,0,0,0,3,2,19950,263.0000,...,False,False,False,False,0,0,0,0,0,0
28,0,0,0,0,0,0,0,0,330959,7.8792,...,False,True,False,False,0,0,0,0,0,0
29,0,0,0,0,0,0,0,0,349216,7.8958,...,False,False,False,False,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861,0,0,0,0,0,0,1,0,28134,11.5000,...,False,False,False,False,0,0,0,0,0,0
862,0,0,0,0,0,0,0,0,17466,25.9292,...,True,False,False,False,0,0,0,0,0,0
863,1,0,0,0,0,0,8,2,CA. 2343,69.5500,...,False,True,False,False,1,0,0,0,0,0
864,0,0,0,0,0,0,0,0,233866,13.0000,...,False,False,False,False,0,0,0,0,0,0
865,0,0,0,0,0,0,0,0,236852,13.0000,...,True,False,False,False,0,0,0,0,0,0
866,0,1,0,1,0,0,1,0,SC/PARIS 2149,13.8583,...,False,True,False,False,0,1,0,1,0,0
867,0,0,1,0,0,0,0,0,PC 17590,50.4958,...,False,False,False,False,0,0,1,0,0,0
868,0,0,0,0,0,0,0,0,345777,9.5000,...,False,False,False,False,0,0,0,0,0,0
869,0,0,0,0,0,0,1,1,347742,11.1333,...,False,False,True,False,0,0,0,0,0,0
870,0,0,0,0,0,0,0,0,349248,7.8958,...,False,False,False,False,0,0,0,0,0,0
871,0,0,0,0,0,0,1,1,11751,52.5542,...,True,False,False,False,0,0,0,0,0,0
872,0,0,0,0,0,0,0,0,695,5.0000,...,False,False,False,False,0,0,0,0,0,0
873,0,0,0,0,0,0,0,0,345765,9.0000,...,False,False,False,False,0,0,0,0,0,0
874,0,0,0,0,0,0,1,0,P/PP 3381,24.0000,...,True,False,False,False,0,0,0,0,0,0
875,0,0,0,0,0,0,0,0,2667,7.2250,...,False,True,False,False,0,0,0,0,0,0
876,0,0,0,0,0,0,0,0,7534,9.8458,...,False,False,False,False,0,0,0,0,0,0
877,0,0,0,0,0,0,0,0,349212,7.8958,...,False,False,False,False,0,0,0,0,0,0
878,0,0,0,0,0,0,0,0,349217,7.8958,...,False,False,False,False,0,0,0,0,0,0
879,0,0,0,0,0,0,0,1,11767,83.1583,...,True,False,False,True,0,0,0,0,0,0
880,0,0,0,0,0,0,0,1,230433,26.0000,...,True,False,False,False,0,0,0,0,0,0
881,0,0,0,0,0,0,0,0,349257,7.8958,...,False,False,False,False,0,0,0,0,0,0
882,0,0,0,0,0,0,0,0,7552,10.5167,...,False,True,False,False,0,0,0,0,0,0
883,0,0,0,0,1,0,0,0,C.A./SOTON 34068,10.5000,...,False,False,False,False,0,0,0,0,1,0
884,0,0,0,0,1,0,0,0,SOTON/OQ 392076,7.0500,...,False,False,False,True,0,0,0,0,1,0
885,0,0,0,0,0,0,0,5,382652,29.1250,...,True,False,False,False,0,0,0,0,0,0
886,0,0,0,0,0,0,0,0,211536,13.0000,...,False,False,False,False,0,0,0,0,0,0
887,0,0,0,0,0,0,0,0,112053,30.0000,...,False,True,False,False,0,0,0,0,0,0
888,0,0,0,0,0,0,1,2,W./C. 6607,23.4500,...,False,True,False,False,0,0,0,0,0,0
889,0,0,0,0,0,0,0,0,111369,30.0000,...,False,False,False,False,0,0,0,0,0,0
890,0,0,0,0,0,0,0,0,370376,7.7500,...,False,False,False,False,0,0,0,0,0,0

In [95]:
train.loc[:,[0, 1, 2, 3, 4, 5]] = vectorizer.fit_transform(train['Ticket']).toarray()
train

KeyError: '[0 1 2 3 4 5] not in index'

In [25]:
test.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [35]:
train['Cabin'].unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27',
       'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33', 'F G73', 'E31',
       'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101', 'F E69', 'D47',
       'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4', 'A32', 'B4',
       'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35', 'C87', 'B77',
       'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19', 'B49', 'D',
       'C22 C26', 'C106', 'C65', 'E36', 'C54', 'B57 B59 B63 B66', 'C7',
       'E34', 'C32', 'B18', 'C124', 'C91', 'E40', 'T', 'C128', 'D37',
       'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44', 'A34', 'C104', 'C111',
       'C92', 'E38', 'D21', 'E12', 'E63', 'A14', 'B37', 'C30', 'D20',
       'B79', 'E25', 'D46', 'B73', 'C95', 'B38', 'B39', 'B22', 'C86',
       'C70', 'A16', 'C101', 'C68', 'A10', 'E68', 'B41', 'A20', 'D19',
       'D50', 'D9', 'A23', 'B50', 'A26', 'D48', 'E58', 'C126', 'B71',
       'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63', 'C62 C64', 'E24', 'C90',
       'C45', 'E8', 'B101', 'D45', 'C46', 'D30', 'E121', 'D11', 'E77',
       'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36', 'B102', 'B69', 'E49',
       'C47', 'D28', 'E17', 'A24', 'C50', 'B42', 'C148'], dtype=object)

In [49]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [110]:
# Import the statsmodels formula API
import statsmodels.formula.api as smf

mod = smf.ols(formula='Survived ~ C(Sex) + np.log(Age) + np.sqrt(Age) + np.sqrt(Fare) + Embarked + Parch + SibSp + CabinLetter + SibSpGT0 + C(Pclass) + mr + mrs + miss + master + jr', data = train).fit()
print(mod.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               Survived   R-squared:                       0.456
Model:                            OLS   Adj. R-squared:                  0.440
Method:                 Least Squares   F-statistic:                     29.00
Date:                Wed, 25 Oct 2017   Prob (F-statistic):           1.01e-96
Time:                        19:31:53   Log-Likelihood:                -350.78
No. Observations:                 891   AIC:                             753.6
Df Residuals:                     865   BIC:                             878.2
Df Model:                          25
Covariance Type:            nonrobust
=======================================================================================
                          coef    std err          t      P>|t|      [95.0% Conf. Int.]
---------------------------------------------------------------------------------------
Intercept               1.1607      0.187      6.213      0.000         0.794     1.527
C(Sex)[T.male]         -0.6160      0.162     -3.801      0.000        -0.934    -0.298
Embarked[T.Q]          -0.0034      0.056     -0.061      0.951        -0.112     0.106
Embarked[T.S]          -0.0600      0.034     -1.753      0.080        -0.127     0.007
Embarked[T.Unknown]    -0.0341      0.265     -0.129      0.897        -0.554     0.486
CabinLetter[T.B]       -0.0010      0.112     -0.009      0.993        -0.221     0.218
CabinLetter[T.C]       -0.0773      0.108     -0.712      0.476        -0.290     0.136
CabinLetter[T.D]        0.0645      0.115      0.559      0.576        -0.162     0.291
CabinLetter[T.E]        0.1288      0.117      1.104      0.270        -0.100     0.358
CabinLetter[T.F]        0.0014      0.150      0.009      0.993        -0.293     0.295
CabinLetter[T.G]       -0.2534      0.216     -1.173      0.241        -0.677     0.171
CabinLetter[T.T]       -0.3603      0.377     -0.956      0.339        -1.100     0.379
CabinLetter[T.U]       -0.1179      0.109     -1.081      0.280        -0.332     0.096
SibSpGT0[T.True]        0.0448      0.040      1.120      0.263        -0.034     0.123
C(Pclass)[T.2]         -0.0080      0.065     -0.124      0.901        -0.135     0.119
C(Pclass)[T.3]         -0.1277      0.066     -1.936      0.053        -0.257     0.002
mr[T.True]              0.0118      0.086      0.138      0.891        -0.157     0.181
mrs[T.True]             0.0033      0.146      0.022      0.982        -0.283     0.290
miss[T.True]           -0.0832      0.144     -0.577      0.564        -0.366     0.200
master[T.True]          0.4919      0.117      4.190      0.000         0.261     0.722
jr[T.True]              0.1457      0.117      1.242      0.215        -0.085     0.376
np.log(Age)            -0.1089      0.050     -2.192      0.029        -0.206    -0.011
np.sqrt(Age)            0.0264      0.018      1.495      0.135        -0.008     0.061
np.sqrt(Fare)           0.0170      0.007      2.371      0.018         0.003     0.031
Parch                  -0.0628      0.019     -3.371      0.001        -0.099    -0.026
SibSp                  -0.0827      0.018     -4.694      0.000        -0.117    -0.048
==============================================================================
Omnibus:                       50.612   Durbin-Watson:                   1.980
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               58.715
Skew:                           0.578   Prob(JB):                     1.78e-13
Kurtosis:                       3.493   Cond. No.                         292.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [31]:
mod.predict(formula='Survived ~ C(Sex) + np.log(Age) + np.sqrt(Age) + np.sqrt(Fare)', exog=train)

AttributeError: 'DataFrame' object has no attribute 'design_info'

In [29]:
help(mod.predict)

Help on method predict in module statsmodels.base.model:

predict(exog=None, transform=True, *args, **kwargs) method of statsmodels.regression.linear_model.OLSResults instance
    Call self.model.predict with self.params as the first argument.

    Parameters
    ----------
    exog : array-like, optional
        The values for which you want to predict.
    transform : bool, optional
        If the model was fit via a formula, do you want to pass
        exog through the formula. Default is True. E.g., if you fit
        a model y ~ log(x1) + log(x2), and transform is True, then
        you can pass a data structure that contains x1 and x2 in
        their original form. Otherwise, you'd need to log the data
        first.
    args, kwargs :
        Some models can take additional arguments or keywords, see the
        predict method of the model for the details.

    Returns
    -------
    prediction : ndarray or pandas.Series
        See self.model.predict

In [32]:
dir(mod)

['HC0_se',
 'HC1_se',
 'HC2_se',
 'HC3_se',
 '_HCCM',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_cache',
 '_data_attr',
 '_get_robustcov_results',
 '_is_nested',
 '_wexog_singular_values',
 'aic',
 'bic',
 'bse',
 'centered_tss',
 'compare_f_test',
 'compare_lm_test',
 'compare_lr_test',
 'condition_number',
 'conf_int',
 'conf_int_el',
 'cov_HC0',
 'cov_HC1',
 'cov_HC2',
 'cov_HC3',
 'cov_kwds',
 'cov_params',
 'cov_type',
 'df_model',
 'df_resid',
 'diagn',
 'eigenvals',
 'el_test',
 'ess',
 'f_pvalue',
 'f_test',
 'fittedvalues',
 'fvalue',
 'get_influence',
 'get_robustcov_results',
 'initialize',
 'k_constant',
 'llf',
 'load',
 'model',
 'mse_model',
 'mse_resid',
 'mse_total',
 'nobs',
 'normalized_cov_params',
 'outlier_test',
 'params',
 'predict',
 'pvalues',
 'remove_data',
 'resid',
 'resid_pearson',
 'rsquared',
 'rsquared_adj',
 'save',
 'scale',
 'ssr',
 'summary',
 'summary2',
 't_test',
 'tvalues',
 'uncentered_tss',
 'use_t',
 'wald_test',
 'wresid']